### ISSUE TITLE
Might want to add httr package dependency to README

### ISSUE THREAD

**Issue by stefanavey** [hrbrmstr/cdcfluview#1]
Tried code in README but failed because `write_disk` function was not found.  Installed and loaded `httr` package and then I was able to use the `get_flu_data` function.

Installing and loading cdcflueview didn't give any errors even though I didn't have the httr package installed (I'm not sure how this works).  In any case, may want to mention this is required in README.

**Comment by hrbrmstr** [comment]
Thx. R should have said something about an httr dependency in a console
message (as that dependency is in the package DEPENDS file) but I'll take a
look.

**Comment by stefanavey** [comment]
You're right.  It does give an error if I remove 'httr' and then try to
install cdcfluview.  Not sure why that didn't happen the first time...  My
best guess is my version of httr was old

thanks

**Comment by hrbrmstr** [comment]
Actually, it's my bad. I had an older version (0.3.0) of httr required in the DESCRIPTION file. I'm pushing 0.2.1 up now to fix. Thx for noting the bug!
