### ISSUE TITLE
"Virgin Islands" warning triggered by example cartogram map code in README.md

### ISSUE THREAD

**Issue by haroldgil** [hrbrmstr/cdcfluview#11]
I get the following warning in using the CDC State FluView map code in the README.md file.

Warning in validate_states(state_data, state_col, merge.x) :
  Found invalid state values: Virgin Islands

The issue seems to be triggered by the line bolded below.

gg_s <- state_flu %>%
  filter(weekend=="Jan-02-2016") %>%
  select(state=statename, value=activity_level) %>%
 **filter(!(state %in% c("Puerto Rico", "New York City"))) %>% # need to add PR to statebins**
  mutate(value=as.numeric(gsub("Level ", "", value))) %>%
  statebins(brewer_pal="RdPu", breaks=4, 
            labels=c("Minimal", "Low", "Moderate", "High"),
            legend_position="bottom", legend_title="ILI Activity Level") +
  ggtitle("CDC State FluView (2015-01-03)")
gg_s

I think that Virgin Islands needs to be added to statebins (like PR used to need it) and should be filtered out in that line in the meantime. Also, it looks like PR was added to statebins, so it can be removed from the filter.

**Comment by hrbrmstr** [comment]
Cool. Thx. They totally changed the API as they got rid of Flash & I think
I need to overhaul everything g this weekend.

**Comment by hrbrmstr** [comment]
I'll be fixing this in the statebins pkg. Closing it here and ref'ing it from there. thx again!

**Comment by hrbrmstr** [comment]
And now it works with the latest `statebins` (re-grab it from GH…major new features)

```
library(cdcfluview)
library(statebins)
library(tidyverse)

flu <- ili_weekly_activity_indicators(2017)

glimpse(flu)

filter(flu, weeknumber == 45) %>% 
  statebins(state_col = "statename", value_col = "activity_level", round = TRUE,
            ggplot2_scale_function = viridis::scale_fill_viridis,
            name = "ILI Activity Level") +
  labs(title="U.S. ILI Weekly Activity : Week #45 / 2017-18") +
  theme_statebins()
```

<img width="673" alt="image" src="https://user-images.githubusercontent.com/509878/32984737-36bcc8dc-cc7a-11e7-905c-bf98c93f4513.png">
