### ISSUE TITLE
fails to install in non-English locales

### ISSUE THREAD

**Issue by bastistician** [hrbrmstr/cdcfluview#17]
When I try to install current **cdcfluview** 0.7.0, I get:
```
* installing *source* package ‘cdcfluview’ ...
** package ‘cdcfluview’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in seq.int(0, to0 - from, by) : 'to' must be a finite number
Error : unable to load R code in package ‘cdcfluview’
ERROR: lazy loading failed for package ‘cdcfluview’
* removing ‘/opt/R/R-3.5.1/site-library/cdcfluview’
```

I found this hard to debug. Especially surprising to me was that the package successfully installs on all platforms on the CRAN check farm (https://cran.r-project.org/web/checks/check_results_cdcfluview.html).

So here is how to trigger the issue in a non-English locale:
```r
library("dplyr")
library("MMWRweek")
source("https://raw.githubusercontent.com/hrbrmstr/cdcfluview/v0.7.0/R/mmwr-map.r")
#> Error in seq.int(0, to0 - from, by) : 'to' must be a finite number
```

The problem is that **cdcfluview** not only defines functions, but also runs code in its `R/mmwr-map.r` source file to generate the `mmwrid_map` data upon installation, which fails if the *locale-dependent* `weekdays()` does not return English names. The problematic code actually resides in the `MMWRweekday()` function of the **MMWRweek** package (https://github.com/jarad/MMWRweek/blob/cbf6afa162402353b2917329a6b00e00c0f4133a/R/MMWRweekday.R#L13-L16) which wrongly assumes that `weekdays()` returns English names. For me, `MMWRweekday("1962-01-01")` returns NA. I have just submitted a corresponding bug report at https://github.com/jarad/MMWRweek/issues/1.

## Workaround

To install **cdcfluview** in a non-English locale, simply start R in a (temporary) environment where LC_TIME=C. Setting this within R (`Sys.setenv("LC_TIME"="C")`) before `install.packages` also worked for me. Package checks on CRAN probably run under LC_TIME=C so the issue does not pop up there.

## Fix

The generation of the `mmwrid_map` data at package installation and the `mmwr_*` functions will start to work in non-English locales once https://github.com/jarad/MMWRweek/issues/1 is fixed.

To directly fix the installation failure of **cdcfluview** in non-English locales, independent of a possible **MMWRweek** update in the future, the auxiliary function `.start_date()` in https://github.com/hrbrmstr/cdcfluview/blob/master/R/mmwr-map.r could be replaced by:
```r
.start_date <- function(year) {
  jan1 <- as.Date(paste0(year, '-01-01'))
  wday <- as.numeric(strftime(jan1, "%w"))  # Sunday is 0
  jan1 - wday + 7*(wday>3)
}
```

**Comment by hrbrmstr** [comment]
This was an _amazing_ bug report! Thank you! Let me see about removing the dependency and implementing the MMR week bits in pkg.

**Comment by hrbrmstr** [comment]
I added your fix to the dev version. I'd like to invite you to add yourself to the DESCRIPTION as a contributor as this is an amazingly helpful fix and a tremendous amount of work on your part to trace down the actual error.
