### ISSUE TITLE
Error in get_state_data() for retrieving multiple seasons of data

### ISSUE THREAD

**Issue by caijun** [hrbrmstr/cdcfluview#2]
Thank you for creating such a great package -`cdcfluview`. It helps me easily download data from FluView.

Just now I used `get_state_data()` to download multiple seasons of FluView data.

```
> state_flu <- get_state_data(c(2013, 2014))
> unique(state_flu$SEASON)
[1] "2013-14"
```

If my understanding for the help file of `get_state_data()`, the results of `unique(state_flu$SEASON)` should be `2013-2014` and `2014-2015`. I guess this may be caused by the update of API of FluView.

**Comment by hrbrmstr** [comment]
a quick glance back at the function doc says: (i.e. 2014 for CDC flu season
2014-2015) so if you want "2012-2013" and "2013-2014" specify 2012:2013.

However, your question uncovered a change in the CDC API that powers their
Flash interface and that the package taps into. I fixed both functions to
use the new format the CDC API expects.

Let me know if you still have issues, tho.

**Comment by caijun** [comment]
Thanks for your quick response. Now it works as the function description describes.
