### ISSUE TITLE
Inconsistent naming of start of week

### ISSUE THREAD

**Issue by asbates** [hrbrmstr/cdcfluview#21]
`ilinet` returns the date of the start of the week as `week_start` but `pi_mortality` returns it as `wk_start` (as well as `wk_end`, `yr_wk_num`). I think a consistent naming scheme would be helpful. 

Is it OK if I submit a pull request for this?

**Comment by hrbrmstr** [comment]
Thank you for working with the package and taking the time to both file and
issue and volunteer to fix something I very likely should have done before
the last CRAN push.

A PR would be amazing! Please ensure to add yourself to the DESCRIPTION as
a contributor. If you have time (it's 100% cool if you do not…the PR alone
for this inconsistency is, as noted, amazing) a package startup message
noting the behavior change as well as some text in the impacted function(s)
would also be helpful for users. I can totally do that part, tho, if you're
pressed for time.

thank you again!
