### ISSUE TITLE
age_group_distribution function error

### ISSUE THREAD

**Issue by Ian-McGovern** [hrbrmstr/cdcfluview#25]
I am now getting an issue when using the age_group_distribution() function. It seems like the last two columns that were being named with the statement below are no longer returned by the API. Removing "publishyearweekid" and "loaddatetime" from the vector 'vir_names' as well as removing "publishyearweekid" from the 'vir_df_cols' resolved the issue. 

Parts of the code that I think caused the issue (from the agd-ipt.r file):

line 44: vir_names <- c("virusid", "ageid", "count", "mmwrid", "seasonid", "publishyearweekid", "loaddatetime")

Lines 56-58:  vir_df_cols <- c("sea_label", "age_label", "vir_label", "count", "mmwrid", "seasonid",
                   "publishyearweekid", "sea_description", "sea_startweek",
                   "sea_endweek", "vir_description",  "vir_startmmwrid", "vir_endmmwrid")

Thanks for all of your work on this great package!

**Comment by hrbrmstr** [comment]
Many thanks for the heads up! It started failing cran checks as well and
Kurt shot me a note as well. Will hopefully get it fixed in the next day or
so.

**Comment by hrbrmstr** [comment]
Looks like it was a quick fix. Doing WinBuilder checks now and will submit to CRAN today if it comes back clean. 

Thanks again!
