### ISSUE TITLE
inflated package size since 0.9.1

### ISSUE THREAD

**Issue by bastistician** [hrbrmstr/cdcfluview#27]
I noticed that the **cdcfluview** tarball grew in size from 25K in version 0.9.0 to over 1M and wondered why. The reason is that the plots from the README are included in `man/figures`. Since the README itself is not included in the package and the figures do not seem to be referenced from any Rd files, these figures could be excluded from the package.

The README seems to have been excluded via `.Rbuildignore` for a reason and I can also see `README_files` (the old location for figures) being excluded. So I guess possible fixes are
- adding `^man/figures/README-.*` to `.Rbuildignore`
- or *not* set knitr's `fig.path = "man/figures/README-"` (I suspect this is done by `hrbrpkghelpr::global_opts()`)

**Comment by hrbrmstr** [comment]
Good catch! #ty!

Lemme nuke the figs and re-submit to CRAN. It should auto-update there w/o issue.

**Comment by hrbrmstr** [comment]
```
Dear maintainer,

thanks, package cdcfluview_0.9.3.tar.gz is on its way to CRAN.

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
  Maintainer: 'Bob Rudis <bob@rud.is>'
```
