### ISSUE TITLE
age_group_distribution function bug

### ISSUE THREAD

**Issue by IMcGovern-Seqirus** [hrbrmstr/cdcfluview#28]
Unfortunately, the CDC updated the meta-data they pass for 'Seasons', which causes an issue for the age_group_distribution function. In xdat, the additional parameter 'IncludeWeeklyRatesAndStrata' is passed for Season. This causes an issue due to an NA column index when joining. 

In the file agd-ipt.r , the issue is resolved by adding in an additional column name (e.g. "sea_includeweeklyratesandstrata") to the of the vector on lines 38-39.

**Comment by hrbrmstr** [comment]
thx. fixed and on CRAN!
