### ISSUE TITLE
Error: Error in read.table(file = file, header = header, sep = sep, quote = quote,  :    more columns than column names

### ISSUE THREAD

**Issue by akitepowell** [hrbrmstr/cdcfluview#3]
Hi,
Useful package for more easily incorporating these data into other analyses.  I've only just started to play with the code you have posted, but I'm getting an error right off the bat.  I could certainly be doing something wrong, but when I run:
flu <- get_flu_data("hhs", 1:10, data_source = c("who", "ilinet"), years=2010:2016)
I get the error:
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names

Also, not sure how interested you are in expanding this, but there's additional influenza related mortality data that are now available - http://www.cdc.gov/flu/weekly/nchs.htm

Aaron

**Comment by hrbrmstr** [comment]
Thx for this report. The CDC may have change the fluview hidden API. I'll take a look

**Comment by hrbrmstr** [comment]
Looks like it's something to do with retrieving data from `who` since

    flu <- get_flu_data("hhs", 1:10, data_source = "ilinet", years=2010:2016)

works OK. I'll post updates here and will also take a look at the mortality data.

**Comment by hrbrmstr** [comment]
hrm. it's an issue with the data format coming down from the hidden fluview api for `who`. The CSV files are malformed. I may be able to work around it.

**Comment by hrbrmstr** [comment]
I think I squashed that bug and I also added a `get_mortality_surveillance_data()` function to grab the data from the URL you linked to.

**Comment by akitepowell** [comment]
This is great, thanks so much.  I'll continue to test to make sure it works on my end.
