### ISSUE TITLE
Pneumonia, influenza, and COIVD mortality data

### ISSUE THREAD

**Issue by mwegener** [hrbrmstr/cdcfluview#32]
The functionality of this package is great but I was wondering if there was any updates to include data on pneumonia, influenza, and COVID (PIC) mortality aside from P&I mortality.

Thank you and again the package has been very helpful so far!

**Comment by mwegener** [comment]
Never mind I figured it out!

**Comment by shauntruelove** [comment]
did this get resolved? the current package appears to not return COVID-19 deaths via the `pi_mortality` function. I cannot get a forked version to work as it cannot find .httr_timeout.

**Comment by mwegener** [comment]
I was able to resolve it on my own by running R code from this GitHub page and adding the variables for COVID. I added an a copy of the rmd file to the GitHub page that Includes some code from the original package that you can try. I titled the patch "COVID19_Deaths".

I labeled each code chunk with the R file name I used from this GitHub page (https://github.com/hrbrmstr/cdcfluview/tree/master/R) and it works for me when I run each chunk one at a time. 

You can see where I added the COVID variables on line 440 (also described in my comment on line 349). I found these extra COVID variables from this CDC website: https://gis.cdc.gov/grasp/flu7/GetPhase07InitApp?appVersion=Public.

The last part of the rmd file includes some SQL code I added which formats the table to look like the CSV file downloaded from the CDC fluview interactive website: https://gis.cdc.gov/grasp/fluview/fluportaldashboard.html

For this to work, I think you need to load the cdcfluview package -> library(cdcfluview). 

If you could please try this and let me know it works for you that would be great.

**Comment by shauntruelove** [comment]
i created a forked repo that includes the COVID-19 deaths in the pi_mortality function. Please feel free to use: `https://github.com/shauntruelove/cdcfluview"`

**Comment by mwegener** [comment]
Thanks for help shauntruelove. Since i am new to github i was wondering if you could show me how to access/use the forked repo. Thanks gain!

**Comment by mwegener** [comment]
Never mind i figured it out. Thanks again!
