### ISSUE TITLE
years=2016

### ISSUE THREAD

**Issue by akitepowell** [hrbrmstr/cdcfluview#5]
When I query for "years=2016" by itself there are not data, any other individual year works, and if I say "years=2015:2016" I do get data from 2016.  Just not by itself.

**Comment by hrbrmstr** [comment]
thx. i'll look into it.

On Mon, Sep 26, 2016 at 3:53 PM, Aaron Kite-Powell <notifications@github.com

**Comment by hrbrmstr** [comment]
it's what i thought it was. The CDC hasn't officially started recording the 2016-2017 flu season. 

![fullscreen_9_26_16__4_57_pm](https://cloud.githubusercontent.com/assets/509878/18851497/5a2170b6-840a-11e6-9374-950449caeb89.png)

If you grab 2015 you'll see that it goes until the last recorded 2016 date:

```r
library(cdcfluview)
library(ggplot2)
library(dplyr)

get_flu_data("hhs", years=2015) %>% 
  mutate(yw=as.Date(sprintf("%04d-%02d-1", YEAR, WEEK), "%Y-%U-%u")) %>% 
  select(region=REGION, yw, pct_weighted_ili=`% WEIGHTED ILI`) %>% 
  mutate(region=factor(region, levels=sprintf("Region %d", 1:10))) %>% 
  mutate(pct_weighted_ili=pct_weighted_ili/100) %>% 
  ggplot(aes(yw, pct_weighted_ili)) -> gg

gg <- gg + geom_line()
gg <- gg + scale_x_date(expand=c(0,0))
gg <- gg + scale_y_continuous(label=scales::percent)
gg <- gg + facet_wrap(~region, ncol=3)
gg <- gg + labs(x=NULL, y=NULL,
                title="% Weighted ILI")
gg <- gg + theme_bw(base_family="Arial Narrow")
gg <- gg + theme(axis.text.x=element_text(margin=margin(0,0,0,0)))
gg <- gg + theme(axis.text.y=element_text(margin=margin(0,0,0,0)))
gg <- gg + theme(axis.ticks=element_blank())
gg <- gg + theme(plot.title=element_text(face="bold", size=16))
gg
```
<img width="946" alt="__development_cdcfluview_-_master_-_rstudio" src="https://cloud.githubusercontent.com/assets/509878/18851481/3db611f2-840a-11e6-8c68-975c6f0e5e14.png">

I tried to keep the pkg aligned with how the CDC presents the seasonal data, but I'm also not an epidemiologist, so if it makes more sense to do it another way, I'm definitely open to changing it.

**Comment by akitepowell** [comment]
I see what you mean, but assumed that since there were data through week 37 2016 (at this point) that if you selected calendar year 2016 it would return whatever data were available.  I think this is minor and no need to change, particularly since you can get the data by selecting the previous season.

**Comment by CTabb83** [comment]
I'm getting this error:

Error in eval(expr, envir, enclos) : object '% WEIGHTED.ILI' not found

Any help would be very much appreciated.

**Comment by hrbrmstr** [comment]
A full reproducible example wld be appreciated.

**Comment by akitepowell** [comment]
Just an FYI - I don't think this is pulling the most recent mortality data available.  Using this code the last date is 9-12-16, but the interactive website has data into Oct 2016.

**Comment by hrbrmstr** [comment]
```r
flu_2016 <- get_flu_data(years=2016)

glimpse(flu_2016)

distinct(flu_2016, YEAR, WEEK) %>% 
  mutate(week=as.Date(sprintf("%04d-%02d-1", YEAR, WEEK), format="%Y-%U-%u"))
## # A tibble: 5 × 3
##    YEAR  WEEK       week
##   <int> <int>     <date>
## 1  2016    40 2016-10-03
## 2  2016    41 2016-10-10
## 3  2016    42 2016-10-17
## 4  2016    43 2016-10-24
## 5  2016    44 2016-10-31
```

**Comment by akitepowell** [comment]
This is for the mortality data?

On Nov 12, 2016 13:10, "boB Rudis" <notifications@github.com> wrote:

>

> flu_2016 <- get_flu_data(years=2016) glimpse(flu_2016) distinct(flu_2016,
YEAR, WEEK) %>% mutate(week=as.Date(sprintf("%04d-%02d-1", YEAR, WEEK),
format="%Y-%U-%u")) ## # A tibble: 5 × 3 ## YEAR WEEK week ## <int> <int>
<date> ## 1 2016 40 2016-10-03 ## 2 2016 41 2016-10-10 ## 3 2016 42
2016-10-17 ## 4 2016 43 2016-10-24 ## 5 2016 44 2016-10-31
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/hrbrmstr/cdcfluview/issues/5#issuecomment-260138569>, or
mute the thread

**Comment by hrbrmstr** [comment]
Yes, as I noted, I looked at the regular flu data first then the mortality data.

I grabbed the first Region 1 CSV _manually_ and it ends at 2016-09-12.

**Comment by akitepowell** [comment]
I agree that it would be nice to have a better interface for extracting these data..  When I visited http://gis.cdc.gov/grasp/fluview/mortality.html data were available up to week 42.  You can get a national csv from this site too - http://www.cdc.gov/flu/weekly/index.htm#MS

**Comment by hrbrmstr** [comment]
I think I fixed this ;-)
