### ISSUE TITLE
years=2017

### ISSUE THREAD

**Issue by nulloa** [hrbrmstr/cdcfluview#7]
Hi,

When running the function `get_flu_data('national', NA)` and omitting the years argument, you get an   error. I think it's because there is no 2017 data yet. This may correct itself in the future, but I just wanted to let you know that it's not working right now. If the argument `years=2016` is included, it works fine.  I guess this is more of a heads up for those of us that use the function without any years argument.

**Comment by hrbrmstr** [comment]
Thx.

It's behaving according to the documented parameter in TFM:

`years` 
_a vector of years to retrieve data for (i.e. 2014 for CDC flu season 2014-2015). Default value is the current year and all years values should be > 1997_

Since the default is to compute the current calendar year, this is expected behavior. Let me see about adding a check for a 0-length data frame and having it auto-try the previous year if a single year was used and it's the current year.

**Comment by hrbrmstr** [comment]
I just pushed a new version to github that does the behavior I mentioned in the previous comment.

It issues a message for this particular condition as well.

    get_flu_data("national")
    Adjusting [years] to get current season...
    ## # A tibble: 12 × 15
    ##    `REGION TYPE` REGION  YEAR  WEEK `% WEIGHTED ILI` `%UNWEIGHTED ILI` `AGE 0-4` `AGE 25-49` `AGE 25-64` `AGE 5-24` `AGE 50-64` `AGE 65` ILITOTAL
    ##              <chr>  <chr> <int> <int>            <dbl>             <dbl>     <int>       <int>       <chr>      <int>       <int>    <int>    <int>
    ##   1       National      X  2016    40          1.20739           1.26774      3106        2141           X       4135         827      638    10847
    ##   2       National      X  2016    41          1.24905           1.31075      3187        2141           X       4030         871      673    10902
    ##   3       National      X  2016    42          1.28271           1.36939      3536        2213           X       4381         952      668    11750
    ##   4       National      X  2016    43          1.37273           1.46587      3743        2375           X       4655         961      678    12412
    ##   5       National      X  2016    44          1.49717           1.60187      4273        2420           X       5140        1009      692    13534
    ##   6       National      X  2016    45          1.57955           1.69099      4659        2504           X       5063        1035      729    13990
    ##   7       National      X  2016    46          1.67721           1.76325      4936        2637           X       5492        1073      817    14955
    ##   8       National      X  2016    47          1.94575           2.10545      5007        2626           X       4559        1117      869    14178
    ##   9       National      X  2016    48          1.85861           1.98807      5235        3382           X       5649        1428     1060    16754
    ##   10      National      X  2016    49          2.01039           2.13984      5362        3179           X       5722        1449     1028    16740
    ##   11      National      X  2016    50          2.30488           2.46889      5513        3414           X       6365        1476      992    17760
    ##   12      National      X  2016    51          2.89491           3.16034      5777        3681           X       6466        1715     1212    18851
    ##   # ... with 2 more variables: `NUM. OF PROVIDERS` <int>, `TOTAL PATIENTS` <int>

**Comment by nulloa** [comment]
awesome! thank you so much!
