### ISSUE TITLE
Hospitalization Surveillance Data

### ISSUE THREAD

**Issue by craigjmcgowan** [hrbrmstr/cdcfluview#8]
Thanks for all of the work you've done putting this package together. Have you considered adding a function to pull laboratory-confirmed hospitalization surveillance data collected by the FluSurv-NET system? The web app is found [here](https://gis.cdc.gov/GRASP/Fluview/FluHospRates.html) and displays cumulative hospitalizations: 
![flusurv_graph](https://cloud.githubusercontent.com/assets/20864042/23263211/860ad098-f9ab-11e6-82e0-2d7ba223a229.PNG)

The data are downloaded as a CSV in the following format:
![flusurv_sheet](https://cloud.githubusercontent.com/assets/20864042/23263212/8821a834-f9ab-11e6-99b2-63fed15febfc.PNG)

I tried to manipulate the `get_flu_data` function but was unable to figure out the API for the hospitalization data.

**Comment by hrbrmstr** [comment]
wow. that's cool data! (and I'm not even in said profession). Serious thanks for the very specific pointers to the data. That is more helpful than you may imagine. Def will be adding this ASAP.

**Comment by hrbrmstr** [comment]
![image](https://cloud.githubusercontent.com/assets/509878/23273285/7b4b89ba-f9cc-11e6-912e-97c40558a81c.png)

So, um…it's going to be a while before this gets in :-)

Towards the top of that DevTools screenshot you'll see a line with "Content-Type: application/x-amf"

As one selects each "Surveillance Area" the Flash app makes a remote connection and receives data in AMF format which is a binary protocol format used by Flash apps for serialization / deserialization of data. 

When you make various selections and click "download data" it literally takes the data that it de-serialized and puts it into CSV format to a thin POST request wrapper:

![image](https://cloud.githubusercontent.com/assets/509878/23273424/f2d57e46-f9cc-11e6-8c86-f2c5e60d026f.png)

(i.e. it's not just sending a query string like the other FluView apps do)

Some Flash dev no doubt thought they were being clever.

To be able to work with this I'll have to figure out if there's a C[++] library for decoding AMF then figure out what I need to do to make this request work (initial attempts to grab the AMF content were not working).

Sigh.

**Comment by craigjmcgowan** [comment]
Hooray for people being clever! I understand the broad strokes of what you're getting at but have no idea how to address it or how to figure that out, which makes me feel a little better about being unable to get it to work myself :-) 

I appreciate you looking into it!

**Comment by hrbrmstr** [comment]
A security comrade found https://github.com/Ventero/amf-cpp & https://github.com/noirotm/libamf so I can encode and decode the blobs now and I figured out what was wrong in the `POST` I was doing. Cant' get to it immediately, but def on the right path.
