### ISSUE TITLE
client error: (411) Length Required

### ISSUE THREAD

**Issue by bastan** [hrbrmstr/cdcfluview#9]
First of all thank you for this nice Packge.

within last days, if I use **get_flu_data**, I get this error: client error: (411) Length Required
Is it a bug in Package?

**Comment by hrbrmstr** [comment]
it likely is a change in their hidden API. i'll take a look today. #ty for
the info.

**Comment by hrbrmstr** [comment]
can you drop a full example? I'm not seeing the same issue (I just tried a plain call to `get_flu_data()` and it worked fine.

**Comment by bastan** [comment]
Thank you for your answer.

I am trying this code:
`library("cdcfluview")
data1 <- get_flu_data(region = "hhs", sub_region = 2, data_source = "ilinet", year = 2008:2017)
newdata <- aggregate(data1$TOTAL.PATIENTS ~ data1$YEAR + data1$WEEK, data = data1, sum)`

**Comment by hrbrmstr** [comment]
This is what I get:

```r
library(cdcfluview)
library(tidyverse)

data1 <- get_flu_data(region = "hhs", sub_region = 2,
                      data_source = "ilinet", year = 2008:2017)

glimpse(data1)
## Observations: 440
## Variables: 15
## $ REGION TYPE       <chr> "HHS Regions", "HHS Regions", "HHS Regions",...
## $ REGION            <chr> "Region 2", "Region 2", "Region 2", "Region ...
## $ YEAR              <int> 2008, 2008, 2008, 2008, 2008, 2008, 2008, 20...
## $ WEEK              <int> 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, ...
## $ % WEIGHTED ILI    <dbl> 0.712588, 0.956882, 0.828672, 0.819794, 0.99...
## $ %UNWEIGHTED ILI   <dbl> 1.11043, 1.23378, 1.19048, 1.18852, 1.25656,...
## $ AGE 0-4           <int> 401, 437, 453, 450, 478, 588, 646, 728, 851,...
## $ AGE 25-49         <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
## $ AGE 25-64         <int> 244, 288, 285, 259, 270, 276, 262, 249, 245,...
## $ AGE 5-24          <int> 310, 366, 337, 360, 371, 424, 415, 411, 503,...
## $ AGE 50-64         <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
## $ AGE 65            <int> 59, 63, 61, 57, 40, 50, 61, 43, 63, 60, 44, ...
## $ ILITOTAL          <int> 1014, 1154, 1136, 1126, 1159, 1338, 1384, 14...
## $ NUM. OF PROVIDERS <int> 71, 82, 87, 89, 89, 94, 95, 96, 99, 95, 97, ...
## $ TOTAL PATIENTS    <int> 91316, 93534, 95424, 94740, 92236, 99690, 97...
newdata <- aggregate(data1$TOTAL.PATIENTS ~ data1$YEAR + data1$WEEK,
                     data = data1, sum)
## Warning: Unknown column 'TOTAL.PATIENTS'
## Error in model.frame.default(formula = data1$TOTAL.PATIENTS ~ data1$YEAR + : invalid type (NULL) for variable 'data1$TOTAL.PATIENTS'
```

The `cdcfluview` call seems fine but you may need to adjust your expected variable names.

**Comment by bastan** [comment]
I am confused now. This is what I get for the function without any parameter and variable

`> get_flu_data()
Error in get_flu_data() : client error: (411) Length Required`

**Comment by hrbrmstr** [comment]
can you post output of `utils::sessionInfo()` ?

**Comment by bastan** [comment]
`> utils::sessionInfo()`
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cdcfluview_0.4.0    RevoUtilsMath_8.0.3 RevoUtils_8.0.3     RevoMods_8.0.3     
[5] RevoScaleR_8.0.3    lattice_0.20-33     rpart_4.1-10       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2      codetools_0.2-14 foreach_1.4.3    dplyr_0.4.3      assertthat_0.1  
 [6] grid_3.2.2       R6_2.1.1         DBI_0.3.1        magrittr_1.5     httr_1.0.0      
[11] pbapply_1.1-3    stringi_1.0-1    curl_0.9.4       xml2_0.1.2       iterators_1.0.8 
[16] tools_3.2.2      stringr_1.0.0    parallel_3.2.2

**Comment by hrbrmstr** [comment]
oh, you need to use the latest CRAN version of `cdcfluview`. it's at 0.5.1 now and it fixed issues with the hidden CDC FluView API changes.

**Comment by bastan** [comment]
Thanks a lot for your help.
Last question:

I have downloaded `cdcfluview_0.5.1.tar.gz`. If I install this it via R Studo I get this error:

Error : Objekt 'map_df' ist nicht von 'namespace:purrr' exportiert
ERROR: lazy loading failed for package 'cdcfluview'

what should I do?

**Comment by hrbrmstr** [comment]
Why not just `install.packages("cdcfluview")` ?
